# This is the final, production-ready configuration for Netlify.

[build]
  command = "npm run build"
  functions = "netlify/functions/"
  publish = "dist"

# This rule allows React Router to work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200